### ISSUE TITLE
Enhancement: Pass a command to the running instance of cgdb from terminal

### ISSUE THREAD

**Issue by xhorak** [cgdb/cgdb#136]
An example:
```
# sets breakpoint to the running instance of cgdb from terminal
$ cgdb-remote "break source.c:13"
```
to be used for example in vim as (not sure with the syntax completely)
```
" set breakpoint to the current file:line by calling cgdb-remote
imap <C-B> !cgdb-remote break expand('%:p'):line(".")
```
or even (if cgdb-remote could print the evaluated command result):
```
" Print value of variable under mouse pointer as a tooltip (does not work in terminal)
function! MyBalloonExpr()
  return system("cgdb-remote print " . eval("v:beval_text"))
endfunction
set bexpr=MyBalloonExpr()
set ballooneval
```
And there's more possible, like up/down the stack in vim.

**Comment by brasko** [comment]
This is a great idea. However, since the project has limited capacity I don't think I'll be working on this right now. In general, CGDB is meant to be used instead of vim when debugging.

It might be interesting to split out a piece of cgdb, from the windowing interface, make a library, and use that for other tools to interact with gdb with.
