### ISSUE TITLE
Any plan to add tty window back? 

### ISSUE THREAD

**Issue by lonAlpha** [cgdb/cgdb#209]
Hi, 

Do you have any plan to add the tty window back? Imperfect feature is better than nothing.  

This feature is very useful for me, and is the only reason I stick to 0.6.8

I often open two panes in tmux, and run cgdb in both panes to compare different behaviour of two revisions. The debug info is printed to tty.  Then I can compare the output in tty window side by side.

I could open two more tmux panes in the same window and attach cgdb to running program. The problem is that I often need to restart program to reach next checkpoint.  
Without tty window, I need to 
  - Close two debuggees
  - Launch two debuggees
  - Attach to two debuggees
  - Restore previous breakpoints and run

With the tty window, I only need to type "run" in both tty window (With tmux synchronized-panes turned on, I only need to type 'run' once). 

![cgdb_tty_tmux](https://user-images.githubusercontent.com/5145579/63151704-adebe700-c03c-11e9-8fb5-cfdc3fcb0933.png)

Thanks,
Yao

**Comment by brasko** [comment]
On Fri, Aug 16, 2019 at 3:56 AM lonAlpha <notifications@github.com> wrote:

> Do you have any plan to add the tty window back? Imperfect feature is
> better than nothing.
>
Yes. Well I should say, the next two features for cgdb are,
- Determining a better way to allow the user to talk to the debugged program
- Switching to GDB/MI communication

I'll be thinking about the communication issue and will post some ideas to
the mailing
list before work is started.

Thanks,
Bob Rossi

**Comment by bmorel** [comment]
Hello. Is there a link somewhere to some discussions about that? A mailing list was mentioned, but I can only find the google group interface, which seems a bit... dead?

I am interested on working on such thing, would help me a lot if cgdb had a patch to support that (I'm trying to implement an alternative to dialog, for several reasons, and debugging is not easy with the tools I know). However, there are several questions I'd have on that, like:

* compatibility: 1) follow posix, 2) be compatible with BSD, 3) linux-only (I'd tend to go way n°2, because of openpty(3)). Windows support would be out of question for me (there is already tons of good debuggers there, and I don't know enough of Windows API nor can even try), which includes the linux layer;
* UI support: 1) spawn or take control of a new real terminal, or 2) emulate one inside cgdb? (I think n°1 would be easier to implement, also would please me to have something I can include in my tiling workflow easily. N°2 seems hard, full of issues considering terminal interpretations of character sequences);
** in case of n°1 above, support for X11 would be the easier, TTY probably harder without root rights at cgdb main process spawn (which I'd prefer to avoid, but maybe on linux capabilities can help, and on *BSDs, well... depends on system?). I have no idea about how to do that in wayland (which is linux-only for now, so not that much interest imo). Re-reading myself make me thinking, the issue about root rights could be mitigated by spawning a cgdb client instead, would add one user manipulation and some code complexity (using named sockets/pipes), but would avoid some security risks;

**Comment by brasko** [comment]
Hi Morel,

Here are the notes I have from when I thought about this last in November.

The most requested CGDB feature is improved inferior communication.

    Today there are 2 windows,
        - the CGDB window
        - the GDB window
    We used to have a TTY window but I foolishly removed it.
    We need to add back the TTY window, but call it a better name, Inferior
(better name?)

    I can see 3 use cases. The user that,
        1) doesn't care about input/output to the debugged program at all
        2) would like to interact with a trivial debugged program (non
curses)
        3) would like to interact with a curses based program

    The first case is supported now in CGDB.
    The second case is solved by adding the inferior windows back into CGDB.
    The third case can be supported by modifying CGDB to allow the inferior
    program to run in another terminal. This can be another terminal window
    or another virtual terminal, in tmux for instance.

    In case 1) and 2) you can start CGDB normally,
        cgdb ...

    In case 3) there are a few options,
        - use the gdb --tty flag to redirect output to another terminal
        - use gdbserver like valgrind does
        - start the program in one terminal, attach from another
        - should cgdb start another xterm or tmux session automatically?
        - ... ?

    To make CGDB more useful, implement case 2) then consider case 3) next.

To answer your questions, we already went down the path of openpty.
This works well on linux, cygwin and maybe one day mingw.

For UI support, the general consensus is that there is no great answer.
Most people I've consulted with have thought it might be best to try to get
that use case working with a tmux integration rather than reinvent the
wheel.
I'm not sure how i feel about this. Or about using something like this,
- https://github.com/TragicWarrior/libvterm
- https://github.com/deadpixi/mtm
People like that cgdb is a single window. Starting a second remote window
on a server to debug may be a nogo. Thoughts?

**Comment by bmorel** [comment]
>     The first case is supported now in CGDB.
    The second case is solved by adding the inferior windows back into CGDB.
    The third case can be supported by modifying CGDB to allow the inferior
    program to run in another terminal. This can be another terminal window
    or another virtual terminal, in tmux for instance.

Until now, I think I worked around case 2 by using a gbd command, something like "set control-terminal /dev/pts/whatever", but I can't even remember a hint to search the exact line, as usual with gdb stuff.

> For UI support, the general consensus is that there is no great answer.

Any coder knows that, I hope :)

> To answer your questions, we already went down the path of openpty.

Is mingw the reason you didn't included it? Or is it included someway I have not noticed?

> For UI support, the general consensus is that there is no great answer.
Most people I've consulted with have thought it might be best to try to get
that use case working with a tmux integration rather than reinvent the
wheel.
I'm not sure how i feel about this. Or about using something like this,
- https://github.com/TragicWarrior/libvterm
- https://github.com/deadpixi/mtm
People like that cgdb is a single window. Starting a second remote window
on a server to debug may be a nogo. Thoughts?

I would say I don't mind if cgdb is one or more windows, because I actually use a tiling window manager, so my windows never go over the others. But I understand it's not the general case. Also, depending on window's paradigms would make cgdb unusable without graphical server. For now, I've had any use for that, I agree, but I am more and more interested in framebuffer stuff, for several reasons. Again, that would not be the normal usage.

I mentioned I am trying to implement an alternative to the `dialog` program, which is a tool to allow shell scripts to spawn ncurses interfaces (useful to allow non-tech people to change stuff over a slow network, for example).
However, it is limited: in shell, you basically capture stdout, so with ncurses stuff, the program have to write it's results somewhere else (stderr, for example), breaking the capture mechanism and making it quite painful to use (this one is the most obvious).

My idea to work against that was to read/write from a given set of file descriptors, eventually provided from command-line by the user (or the script, which could use `$(tty)` to retrieve it's own in/out). Got a quick PoC on linux, seems ok, but I need to be able to debug the real thing without too much pain.

For cgdb, I guess I'd like it to become the terminal, but that would imply forwarding signals (about term resize) to the debugged application and going fully background until a (combination of) key is pressed. This might make things "easy" *cough* since then the multiple ncurses interfaces would not fight themselves? Maybe you knew [softice](https://en.wikipedia.org/wiki/SoftICE)? Something like that, inverted, and without the ring 0 stuff?
Just got that idea, not sure how it could be done, but you asked for thoughts, so I tried?

**Comment by lonAlpha** [comment]
> People like that cgdb is a single window. Starting a second remote window on a server to debug may be a nogo.

It is true for me. I am a heavy user of tmux/vim/cgdb.  My graphical desktop on server is not stable enough and ssh/terminal is much better. 

If multiple windows or even GUI is an option, I would have turn to Emacs, or even [TotalView](https://www.roguewave.com/products-services/totalview).

**Comment by brasko** [comment]
Thanks for sharing that. We wouldn't get rid of the workflow you use, there
are way to many people in that workflow to even consider it.

**Comment by brasko** [comment]
Hi,

Could you guys try out the new-ui branch?

You can now send text to gdb or the debugged program, the same way you would without gdb.

I suspect it will resolve your issue, please let me know.

**Comment by brasko** [comment]
I've pushed a change that allows you to communicate with the inferior just as you would with gdb.
This should be resolved now.
