### ISSUE TITLE
Any plans for supporting [i]?pdb?

### ISSUE THREAD

**Issue by vmiheer** [cgdb/cgdb#216]
I love cgdb, I have previously used it with android gdb etc. I was wondering if I can use cgdb with `-d 'python -m ipdb'`.

**Comment by iandinwoodie** [comment]
We are glad you find the cgdb project helpful! The scope of this project is "a lightweight curses (terminal-based) interface to the GNU Debugger (GDB)." Here is the section line from the GDB website:

> What Languages does GDB Support?
>
> GDB supports the following languages (in alphabetical order):
Ada
Assembly
C
C++
D
Fortran
Go
Objective-C
OpenCL
Modula-2
Pascal
Rust

Therefore, adding support for the Python debugger (`pdb) and iPython debugger (`ipdb`) are currently outside of the scope of this project. If we ever change our minds on that decision, we will reopen this issue so that you are notified of the change.

**Comment by dstromberg** [comment]
I'd really like this too - but I'm hearing that pdb doesn't support multithreading, so it'd be better to support the backend from winpdb or similar.

Winpdb itself appears to be moribund :(
