### ISSUE TITLE
Version number incorrect in welcome screen

### ISSUE THREAD

**Issue by dflogeras** [cgdb/cgdb#240]
Now that my distro has bumped up to the 0.7.x series, I noticed that CGDB's welcome screen still reports the version as 0.6.8..  I see that there is an interactive autorelease.sh script, but I'd bet distros are not using that and just running configure, make, make install which seems to default to v0.6.8. as in configure.init line 3.

This probably will cause confusion in bug reports if users report an incorrect version with a bug.

**Comment by brasko** [comment]
Thanks for pointing this out. I'll attempt to address this for the next release.

**Comment by WilliamLeoV** [comment]
I use following code to get git version. And if not git project, the version can be write in file "Version"
`echo "-- Update configure.in to reflect the new version number"

if [ -a "./.git/config" ]
then
  GIT_VER=`git reflog | head -n 1 | awk '{print $1}'`
else
  if [ -s "./Version" ]
  then
    GIT_VER=`head -n 1 ./Version | awk '{print $1}'`
  else
    GIT_VER="Unknown"
  fi
fi`

**Comment by brasko** [comment]
I just took a look at this and am slightly confused.

If people use a release tarball, then they'll have the right version from the tarball.
If people build from source, by running autogen.sh, configure, make, then we substitute in a date, like so:
  $ ./cgdb/cgdb --version
  CGDB 20210311

I'll have to close this case as not reproducible, please let me know otherwise and I'll take a look.

**Comment by dflogeras** [comment]
@brasko 

I confirmed that gentoo is using this tarball as a source:
https://github.com/cgdb/cgdb/archive/v0.7.1.tar.gz

If I manually unpack that, and look inside configure.init, it is calling AC_INIT( cgdb, 0.6.8 ) which I believe in turn generates the version string?
