### ISSUE TITLE
CGDB does not suppress output of current line when stepping anymore

### ISSUE THREAD

**Issue by gergap** [cgdb/cgdb#262]
It is normal that's gdb prints the current line when stepping. Somehow this was suppressed within cgdb, which makes sense.
You see the current position in the code window and don't want to flood the gdb window below with this information.

However, in the latest version this "filter" does not work anymore.
Using "git bisect" I found the breaking change.

It is commit:0a16115c92c043626ff702ad67226ab6f2260715 "Major CGDB update".
Unfortunately, it's a big change with lots of rewritten code.

I hope the author can restore the old behavior.

This happened with "GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git", but I'm pretty confident that this happens with other versions too.

**Comment by brasko** [comment]
Please see case #223. https://github.com/cgdb/cgdb/issues/223

This is actually a gdb issue and would need to be fixed in gdb.

When using a2 (an old way to talk to gdb) gdb would not print this line. When using mi it does.
I'll close this as it's not something that cgdb can address, but would have to be fixed upstream in gdb.
