### ISSUE TITLE
[bug] Alt-. cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [cgdb/cgdb#320]
In gdb, `<Alt-.>` (or `<Meta-.>`) is a hotkey to retype the last word of last input. However, in cgdb, `<Alt-.>` always be recognized as `<Esc>.`, but `<Alt-b>`, `<Alt-f>`, etc will work normally. So I doubt this is a bug.

**Comment by brasko** [comment]
The issue here is that <Alt-.> is being sent as ESC to GDB and CGDB.
ESC is the cgdbmodekey, which tells cgdb to go from gdb mode to cgdb mode.
You can choose a different cgdbmodekey if you prefer, 'set cgdbmodekey=<F2>' for instance.
Then the behavior you are requesting should work.
I'm going to close this case, if the answer doesn't work for you, please reopen.
