### ISSUE TITLE
Debugged programs should not detect a terminal, until terminal sequence handling is fixed

### ISSUE THREAD

**Issue by yurivict** [cgdb/cgdb#61]
Currently terminal sequences are printed w/out being interpreted, trashing up the output.

I understand that this may be difficult to fix. So you just need to turn off the bit returned by "isatty(fileno(stdout))".

**Comment by mmueller** [comment]
This is a really good suggestion. It would be awesome if the gdb pane was a
full terminal. But since it's not, if we can make sure programs know it's
not a tty, that's an improvement.

**Comment by zed0** [comment]
If it's only colours you're wanting, I've added a hack in for basic 16 colour support in my fork: https://github.com/zed0/cgdb
It's liable to pick up false positives from things that look sort of like ANSI sequences because the 0x1B character is swallowed somewhere on the way, but other than that it works reasonably.

Disclaimer: I realise that this is a non-ideal way to resolve this, and that there are more elegant solutions in the pipeline, this is just something I hacked together quickly.

**Comment by yurivict** [comment]
I was more after not seeing raw terminal escape sequences. Colors are rarely important during debugging. But these terminal sequences are distracting.

Ideally cgdb should redirect output into the separate window with the real terminal emulation, not just print into the same window. But this might be difficult to do.

**Comment by brasko** [comment]
On Fri, May 22, 2015 at 02:30:52AM -0700, yurivict wrote:
> I was more after not seeing raw terminal escape sequences. Colors are rarely important during debugging. But these terminal sequences are distracting.
> 
> Ideally cgdb should redirect output into the separate window with the real terminal emulation, not just print into the same window. But this might be difficult to do.

The way I recommend doing this today is starting the program you would
like to debug from the terminal, and then attaching to it with cgdb from
another terminal. This is easier to do if you use a terminal emulator
like tmux or screen. This approach doesn't work great when you have to
debug the startup of the executable, so eventually I'll be working on a
solution for that as well.

Thanks,
Bob Rossi

**Comment by mikesart** [comment]
Most color escape sequences should work now. If you're still having issues, please re-open with a new bug and repro details. Thanks!
